[tox]
env_list = py310, py311, py312, py313, py314
requires =
    tox-uv

[testenv]
package = wheel
runner = uv-venv-lock-runner
commands_pre =
    uv sync --active --frozen --system-certs --python {envpython}

commands =
    coverage run -m pytest -v --color=yes --basetemp="{envtmpdir}" {posargs}
    coverage report
    coverage html -d {envtmpdir}/htmlcov
    python test.py
